### ISSUE TITLE
`racket-run` within not-modified buffer w/o associated file

### ISSUE THREAD

**Issue by jasonhemann** [greghendershott/racket-mode#626]
If I am in a `racket-mode` buffer without an associated file, and that buffer is in the not-modified state, and then I attempt to `racket-run`, I see an error reporting `Wrong type argument: racket--what-to-run-p, (nil)`. 

I can create a scratch buffer, set that buffer to racket mode, add some text like the following, `M-x not-modified` to clear the modified flag, and then `C-c r` to invoke `racket-run` and I face this error. 

```
#lang racket
(define x 5)
```
When the buffer is in the modified state, I'm first offered a prompt to save the buffer to a file so this issue doesn't come up. Is this all intended, correct behavior? This example is artificial, but I came across the issue when trying to call `racket-run` from the racket-moded edit window that results from calling `org-edit-src-code` in a source block . 

<details>
<pre>
((alist-get 'racket-mode package-alist))
((emacs-version "28.1")
 (system-type darwin)
 (x-gtk-use-system-tooltips UNDEFINED)
 (major-mode racket-mode)
 (racket--el-source-dir "/Users/jhemann/.emacs.d/straight/build/racket-mode/")
 (racket--rkt-source-dir "/Users/jhemann/.emacs.d/straight/build/racket-mode/racket/")
 (racket-program "racket")
 (racket-command-timeout 10)
 (racket-path-from-emacs-to-racket-function UNDEFINED)
 (racket-path-from-racket-to-emacs-function UNDEFINED)
 (racket-browse-url-function racket-browse-url-using-temporary-file)
 (racket-documentation-search-location "https://docs.racket-lang.org/search/index.html?q=%s")
 (racket-xp-after-change-refresh-delay 1)
 (racket-xp-mode-lighter
  (:eval
   (racket--xp-mode-lighter)))
 (racket-xp-highlight-unused-regexp "^[^_]")
 (racket-repl-buffer-name-function nil)
 (racket-submodules-to-run
  ((test)
   (main)))
 (racket-memory-limit 2048)
 (racket-error-context medium)
 (racket-repl-history-directory "~/.emacs.d/racket-mode/")
 (racket-history-filter-regexp "\\`\\s *\\'")
 (racket-images-inline t)
 (racket-imagemagick-props nil)
 (racket-images-keep-last 100)
 (racket-images-system-viewer "open")
 (racket-pretty-print t)
 (racket-use-repl-submit-predicate nil)
 (racket-pretty-print t)
 (racket-indent-curly-as-sequence t)
 (racket-indent-sequence-depth 0)
 (racket-pretty-lambda nil)
 (racket-smart-open-bracket-enable nil)
 (racket-module-forms "\\s(\\(?:module[*+]?\\|library\\)")
 (racket-logger-config
  ((cm-accomplice . warning)
   (GC . info)
   (module-prefetch . warning)
   (optimizer . info)
   (racket/contract . error)
   (racket-mode-debugger . info)
   (sequence-specialization . info)
   (* . fatal)))
 (racket-show-functions
  (racket-show-pseudo-tooltip)))
(enabled-minor-modes
 (anzu-mode)
 (auto-composition-mode)
 (auto-compression-mode)
 (auto-encryption-mode)
 (auto-fill-mode)
 (auto-save-mode)
 (buffer-read-only)
 (column-number-mode)
 (company-mode)
 (display-line-numbers-mode)
 (display-time-mode)
 (el-patch-use-package-mode)
 (electric-indent-mode)
 (electric-quote-mode)
 (eshell-vterm-mode)
 (file-name-shadow-mode)
 (flyspell-lazy-mode)
 (font-lock-mode)
 (global-anzu-mode)
 (global-company-mode)
 (global-display-line-numbers-mode)
 (global-eldoc-mode)
 (global-flycheck-mode)
 (global-font-lock-mode)
 (global-git-commit-mode)
 (global-visual-line-mode)
 (hs-minor-mode)
 (line-number-mode)
 (mac-auto-operator-composition-mode)
 (mac-mouse-wheel-mode)
 (magit-auto-revert-mode)
 (menu-bar-mode)
 (org-roam-db-autosync-mode)
 (override-global-mode)
 (paredit-mode)
 (prescient-persist-mode)
 (racket-smart-open-bracket-mode)
 (racket-xp-mode)
 (save-place-mode)
 (savehist-mode)
 (selectrum-mode)
 (selectrum-prescient-mode)
 (semantic-minor-modes-format)
 (shell-dirtrack-mode)
 (show-paren-mode)
 (smartparens-mode)
 (smartparens-strict-mode)
 (straight-package-neutering-mode)
 (straight-use-package-mode)
 (tooltip-mode)
 (transient-mark-mode)
 (visual-line-mode)
 (volatile-highlights-mode)
 (which-key-mode)
 (wrap-region-global-mode)
 (wrap-region-mode)
 (ws-butler-global-mode))
(disabled-minor-modes
 (abbrev-mode)
 (artbollocks-mode)
 (auto-fill-function)
 (auto-image-file-mode)
 (auto-revert-mode)
 (auto-revert-tail-mode)
 (auto-save-visited-mode)
 (avy-linum-mode)
 (bibtex-completion-notes-global-mode)
 (bibtex-completion-notes-mode)
 (blink-cursor-mode)
 (buffer-face-mode)
 (bug-reference-mode)
 (bug-reference-prog-mode)
 (button-mode)
 (cdlatex-mode)
 (cl-old-struct-compat-mode)
 (company-search-mode)
 (compilation-minor-mode)
 (compilation-shell-minor-mode)
 (completion-in-region-mode)
 (context-menu-mode)
 (dash-fontify-mode)
 (defining-kbd-macro)
 (diff-auto-refine-mode)
 (diff-minor-mode)
 (dired-hide-details-mode)
 (dired-isearch-filenames-mode)
 (dired-omit-mode)
 (diredp-breadcrumbs-in-header-line-mode)
 (doc-view-minor-mode)
 (doc-view-presentation-mode)
 (edebug-mode)
 (edit-indirect--overlay)
 (eldoc-mode)
 (electric-layout-mode)
 (ert--current-run-stats)
 (eshell-arg-mode)
 (flycheck-mode)
 (flyspell-mode)
 (flyspell-popup-auto-correct-mode)
 (git-commit-mode)
 (global-auto-revert-mode)
 (global-dash-fontify-mode)
 (global-dired-hide-details-mode)
 (global-hl-line-mode)
 (global-prettify-symbols-mode)
 (global-semantic-highlight-edits-mode)
 (global-semantic-highlight-func-mode)
 (global-semantic-show-parser-state-mode)
 (global-semantic-show-unmatched-syntax-mode)
 (global-semantic-stickyfunc-mode)
 (global-whitespace-mode)
 (global-whitespace-newline-mode)
 (gnus-dead-summary-mode)
 (gnus-undo-mode)
 (hl-line-mode)
 (hmouse-dired-display-here-mode)
 (horizontal-scroll-bar-mode)
 (hycontrol-frames-mode)
 (hycontrol-local-frames-mode)
 (hycontrol-local-windows-mode)
 (hycontrol-windows-mode)
 (hyperbole-mode)
 (ido-everywhere)
 (image-dired-minor-mode)
 (image-minor-mode)
 (impatient-mode)
 (indent-tabs-mode)
 (isearch-mode)
 (ispell-minor-mode)
 (jit-lock-debug-mode)
 (lock-file-mode)
 (mac-auto-ascii-mode)
 (mac-font-panel-mode)
 (magit-blame-mode)
 (magit-blame-read-only-mode)
 (magit-blob-mode)
 (magit-popup-help-mode)
 (magit-wip-after-apply-mode)
 (magit-wip-after-save-local-mode)
 (magit-wip-after-save-mode)
 (magit-wip-before-change-mode)
 (magit-wip-initial-backup-mode)
 (magit-wip-mode)
 (mail-abbrevs-mode)
 (markdown-live-preview-mode)
 (midnight-mode)
 (minibuffer-electric-default-mode)
 (mml-mode)
 (mouse-wheel-mode)
 (next-error-follow-minor-mode)
 (org-bullets-mode)
 (org-capture-mode)
 (org-cdlatex-mode)
 (org-list-checkbox-radio-mode)
 (org-src-mode)
 (org-table-follow-field-mode)
 (org-table-header-line-mode)
 (org-trello-mode)
 (orgtbl-mode)
 (outline-minor-mode)
 (overwrite-mode)
 (paragraph-indent-minor-mode)
 (paredit-everywhere-mode)
 (prettify-symbols-mode)
 (rst-minor-mode)
 (semantic-highlight-edits-mode)
 (semantic-highlight-func-mode)
 (semantic-mode)
 (semantic-show-parser-state-mode)
 (semantic-show-unmatched-syntax-mode)
 (semantic-stickyfunc-mode)
 (server-mode)
 (sh-electric-here-document-mode)
 (shell-command-with-editor-mode)
 (show-smartparens-global-mode)
 (show-smartparens-mode)
 (size-indication-mode)
 (smartparens-global-mode)
 (smartparens-global-strict-mode)
 (smerge-mode)
 (straight-live-modifications-mode)
 (straight-symlink-emulation-mode)
 (tab-bar-history-mode)
 (tab-bar-mode)
 (table-fixed-width-mode)
 (table-mode-indicator)
 (temp-buffer-resize-mode)
 (text-scale-mode)
 (tool-bar-mode)
 (transient-resume-mode)
 (unify-8859-on-decoding-mode)
 (unify-8859-on-encoding-mode)
 (url-handler-mode)
 (use-hard-newlines)
 (vc-parent-buffer)
 (view-mode)
 (visible-mode)
 (vterm-copy-mode)
 (w3m-fb-mode)
 (w3m-minor-mode)
 (wc-mode)
 (which-function-mode)
 (whitespace-mode)
 (whitespace-newline-mode)
 (window-divider-mode)
 (with-editor-mode)
 (wordsmith-mode)
 (writegood-mode)
 (ws-butler-mode)
 (xref-etags-mode))
</pre>
</details>

**Comment by greghendershott** [comment]
I'm pretty sure I fixed this about a month ago in commit 9d06ad1. (Maybe I should have created an issue here for it.) Does upgrading fix it for you, too?

**Comment by greghendershott** [comment]
After looking at this again, I'm 99% sure this is resolved by commit 9d06ad1 so I'm going to go ahead and close this.

But of course please don't hesitate to reopen if updating doesn't fix this!

**Comment by greghendershott** [comment]
Commit 9d06ad1 first fixed it. I mentioned that earliest fix because I didn't know when you'd upgraded.

Commit 2477f07 later changed the approach -- fixed it another, simpler way.

**Comment by jasonhemann** [comment]
Well, even after ensuring I'm up to date, I'm still see this `racket--what-to-run-p` behavior. A racket-mode buffer without an associated file, clear the modification flag, and I still get sent to this failure path. Can you replicate?

**Comment by greghendershott** [comment]
The steps I was trying were based on the problem I'd originally noticed, and fixed. For example:

1. `M-x find-file`, enter `/var/tmp/foo.rkt` (which doesn't yet exist).
2. Enter say `#lang racket` in the buffer.
3. `M-x racket-run-module-at-point`.

And I verified again just now this does work fine.

But I'm realizing I didn't _really_ follow your steps, exactly. When I try those, now, yes, I can reproduce it. :disappointed: I am so sorry. I'll reopen this.

---

I'll investigate. Meanwhile, one disclaimer: Racket Mode currently can only run code in a file that exists. (That's part of what `racket--what-to-run-p` is testing, as a sanity check.) So the step where you do `M-x not-modified`, is where things are going wrong in terms of Racket Mode's assumptions.

In fact, when I first read your report, I assumed `M-x not-modified` was something you'd done just for a bug report recipe -- not something you wanted to do in real use. Maybe that's even how I misled myself into thinking you were reporting the other problem I had fixed, and just using my own steps.

If your desire is for Racket Mode to be able to run code that's not in a saved file, that's something it can't currently do, and probably can't do in the foreseeable future.

In any case, again I am so sorry for the confusion I caused above!

**Comment by greghendershott** [comment]
p.s. And so the problem I fixed about a month ago, is that sometimes Racket Mode was not automatically saving the buffer before trying to run. The fix was to ensure it saves automatically (assuming the not-modified buffer flag is telling the truth wrt file on disk). Saving before run is something it's done for like 10 years, until it broke in some edge cases when I added the multiple back end support (and then fixed it about a month ago).

**Comment by greghendershott** [comment]
p.p.s. So it sounds like the core issue, for you, is the usage from `org-edit-src-code`. I'll try to get some hands-on experience using that, myself, and think about what can be done.

**Comment by greghendershott** [comment]
I'm still amazed how badly I misread the original bug report.

Anyway, I have an idea how to address this. When `racket-run` is done on a buffer for which `buffer-file-name` is `nil` -- which is the case for buffers created using your recipe above, as well as by `org-edit-src-code` -- then we can set `buffer-file-name` to a temporary file and write to that.

In other words I can't (in the foreseeable future) change Racket Mode's requirement that running needs an existing file. But I can automatically create such a file for you.

This works for me for example using the following minimal example org-mode buffer:

```
# -*- org-src-lang-modes: (("racket" . racket)); -*-
#+BEGIN_SRC racket
  #lang racket/base
  "hello"
#+END_SRC
```

I can <kbd>C- '</kbd>, and in the resulting `racket-mode` buffer do <kbd>C-c C-c</kbd> successfully.

**Comment by jasonhemann** [comment]
This works great! Thank you very much for all the help!!
